import { OneTimeDonation, Subscription } from "@prisma/client";

type Donation = Subscription | OneTimeDonation

export const donations: Donation[] = [
    {
      id: "1",
      userId: "user1",
      amount: 10,
      currency: "USD",
      frequency: "monthly",
      anonymous: false,
      stripeSessionId: "sess_12345",
      status: "completed",
      message: "Keep up the good work!",
      createdAt: new Date("2023-01-01"),
      updatedAt: new Date("2023-01-01"),
    },
    {
      id: "2",
      userId: "user2",
      amount: 20,
      currency: "EUR",
      frequency: "yearly",
      anonymous: true,
      stripeSessionId: "sess_67890",
      status: "completed",
      message: "",
      createdAt: new Date("2023-02-01"),
      updatedAt: new Date("2023-02-01"),
    },
    {
      id: "3",
      userId: "user1",
      amount: 15,
      currency: "GBP",
      frequency: "onetime",
      anonymous: false,
      stripeSessionId: "sess_13579",
      status: "completed",
      message: "Happy to support!",
      createdAt: new Date("2023-03-01"),
      updatedAt: new Date("2023-03-01"),
    },
    {
      id: "4",
      userId: "user3",
      amount: 50,
      currency: "USD",
      frequency: "monthly",
      anonymous: false,
      stripeSessionId: "sess_24680",
      status: "completed",
      message: "Great cause!",
      createdAt: new Date("2023-04-01"),
      updatedAt: new Date("2023-04-01"),
    },
    {
      id: "5",
      userId: "user2",
      amount: 100,
      currency: "EUR",
      frequency: "onetime",
      anonymous: true,
      stripeSessionId: "sess_54321",
      status: "completed",
      message: "",
      createdAt: new Date("2023-05-01"),
      updatedAt: new Date("2023-05-01"),
    },
    {
      id: "6",
      userId: "user3",
      amount: 5,
      currency: "GBP",
      frequency: "monthly",
      anonymous: false,
      stripeSessionId: "sess_98765",
      status: "completed",
      message: "Happy to help!",
      createdAt: new Date("2023-06-01"),
      updatedAt: new Date("2023-06-01"),
    },
  ];
 